title: Built Environment Edinburgh
tagline: to create a sustainable and resilient environment
description: >
  GitHub Page Powered by Jekyll

# Required for GitHub Pages
url: "https://ruibogithub.github.io"
baseurl: "/built-environment-edinburgh"
google_analytics: G-XXXXXXX
markdown: kramdown
theme: jekyll-theme-cayman
sass:
  style: expanded
nav:
  - name: Home
    link: /built-environment-edinburgh/
  - name: People
    link: /built-environment-edinburgh/people/
  - name: Projects
    link: /built-environment-edinburgh/projects/
  - name: Resources
    link: /built-environment-edinburgh/resources/