title: Built Environment Edinburgh
tagline: to create a sustainable and resilient environment
description: >
  A minimal clean research group website powered by Jekyll and GitHub Pages.

# Required for GitHub Pages
url: "https://ruibogithub.github.io"
baseurl: "/built-environment-edinburgh"   # your repo name

markdown: kramdown
theme: null
sass:
  style: expanded

# Navigation menu
nav:
  - name: Home
    link: /
  - name: About
    link: /built-environment-edinburgh/about/
  - name: People
    link: /built-environment-edinburgh/people/
  - name: Projects
    link: /built-environment-edinburgh/projects/

