title: Built Environment Edinburgh
tagline: to create a sustainable and resilient environment
description: >
  A minimal clean research group website powered by Jekyll and GitHub Pages.

markdown: kramdown
theme: null        # we use our own layouts
sass:
  style: expanded

# Navigation menu
nav:
  - name: Home
    link: /
  - name: About
    link: /about
  - name: People
    link: /people
  - name: Projects
    link: /projects