title: Built Environment Edinburgh
tagline: to create a sustainable and resilient environment
description: >
  A minimal clean research group website powered by Jekyll and GitHub Pages.

# Required for GitHub Pages
url: "https://ruibogithub.github.io"
baseurl: "/built-environment-edinburgh"   # your repo name

markdown: kramdown
theme: null
sass:
  style: expanded

# Navigation menu
nav:
  - name: Home
    link: "{{ '/' | relative_url }}"
  - name: About
    link: "{{ '/about/' | relative_url }}"
  - name: People
    link: "{{ '/people/' | relative_url }}"
  - name: Projects
    link: "{{ '/projects/' | relative_url }}"
